# Project: Arvore234
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o arvore234.o
LINKOBJ  = main.o arvore234.o
LIBS     = -L"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/lib" -L"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/include" -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/include" -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/Giovane/Desktop/Instaladores/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = Arvore234.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

arvore234.o: arvore234.cpp
	$(CPP) -c arvore234.cpp -o arvore234.o $(CXXFLAGS)
